name: 🚀 Feature Request
description: Request a feature/enhancement
title: '[Enhancement]: '
labels: ['enhancement']
body:
  - type: dropdown
    id: enhancement-type
    attributes:
      label: Type of Enhancement
      options:
        - Feature
        - Code
        - UI
        - Documentation
  - type: textarea
    id: describe
    attributes:
      label: Describe the Feature/Enhancement
      description: Please help us understand what you want.
      placeholder: What is your vision?
    validations:
      required: true
  - type: textarea
    id: the-why
    attributes:
      label: Why would this be helpful?
      description: Please help us understand why this would enhance your experience.
      placeholder: Explain the "why" or "use case".
    validations:
      required: true
