name: 🔧 Installation issue
description: If you have any issue during the installation
title: '[Installation issue]: '
labels: ['install issue']
body:
  - type: markdown
    attributes:
      value: '🦜 Thanks for taking the time to fill out this installation issue!'
  - type: markdown
    attributes:
      value: 'Please first check if the issue is listed into issues.'
  - type: dropdown
    id: missing-requirement
    attributes:
      label: Does this issue concern a missing requirement?
      options:
        - No
        - Yes (fill in the missing package below)
    validations:
      required: true
  - type: textarea
    id: missing-package
    attributes:
      label: Missing Requirement
      description: If the issue is due to a missing package, specify which one(s) here.
      placeholder: e.g., libssl-dev, sqlite3, VLC
  - type: markdown
    attributes:
      value: '---'
  - type: markdown
    attributes:
      value: 'If your issue **does not** concern a missing requirement, continue below (otherwise, you can submit now).'
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Tell us what you see and give a screenshot if it's applicable.
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the issue
      value: '1. '
  - type: markdown
    attributes:
      value: '## Install Environment'
  - type: input
    id: version
    attributes:
      label: Toutui version that you try to install
      description: Do not put 'Latest version', please put the actual version here
      placeholder: 'e.g. v0.1.0-beta'
  - type: dropdown
    id: install-distro
    attributes:
      label: On which OS are you trying to install Toutui?
      options:
        - Arch Linux
        - Ubuntu
        - Debian
        - macOS
        - Other (list in "Additional Notes" box)
  - type: dropdown
    id: install-method
    attributes:
      label: Which install method?
      options:
        - Easy installation 
        - Yay
        - Git (manual)
        - Other (list in "Additional Notes" box)
  - type: textarea
    id: error-message
    attributes:
      label: Error message
      description: Error message during the installation
      placeholder: Paste message here
  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Anything else you want to add?
