name: Build Binaries

on:
  release:
    types: [published] 

jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-apple-darwin]

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/${{ matrix.target }}/release/toutui
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

